enum QueueType {
  OFFLINE_QUEUE = 0,
  INBOUND_QUEUE = 1,
  OUTBOUND_IVR_QUEUE = 2,
  PREVIEW_DIALER = 3,
  PROGRESSIVE_DIALER = 4,
  PREDICTIVE_DIALER = 5,
  CHAT_INBOUND_QUEUE = 6,
  INBOUND_TASK_QUEUE = 7,
  OUTBOUND_TASK_QUEUE = 8,
}

export default QueueType
