// tslint:disable
/**
 * Webitel API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 24.04.0
 * Contact: support@webitel.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface AggregateRequestGroup
 */
export interface AggregateRequestGroup {
  /**
   *
   * @type {string}
   * @memberof AggregateRequestGroup
   */
  aggregate?: string
  /**
   *
   * @type {boolean}
   * @memberof AggregateRequestGroup
   */
  desc?: boolean
  /**
   *
   * @type {string}
   * @memberof AggregateRequestGroup
   */
  field?: string
  /**
   *
   * @type {string}
   * @memberof AggregateRequestGroup
   */
  id?: string
  /**
   *
   * @type {string}
   * @memberof AggregateRequestGroup
   */
  interval?: string
  /**
   *
   * @type {number}
   * @memberof AggregateRequestGroup
   */
  top?: number
}
