// tslint:disable
/**
 * Webitel API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 24.04.0
 * Contact: support@webitel.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ApiLDAPDeleteLDAPTemplateBody
 */
export interface ApiLDAPDeleteLDAPTemplateBody {
  /**
   *
   * @type {string}
   * @memberof ApiLDAPDeleteLDAPTemplateBody
   */
  base_dn?: string
  /**
   *
   * @type {boolean}
   * @memberof ApiLDAPDeleteLDAPTemplateBody
   */
  disabled?: boolean
  /**
   *
   * @type {boolean}
   * @memberof ApiLDAPDeleteLDAPTemplateBody
   */
  enabled?: boolean
  /**
   *
   * @type {Array<string>}
   * @memberof ApiLDAPDeleteLDAPTemplateBody
   */
  fields?: Array<string>
  /**
   *
   * @type {Array<string>}
   * @memberof ApiLDAPDeleteLDAPTemplateBody
   */
  id?: Array<string>
  /**
   *
   * @type {string}
   * @memberof ApiLDAPDeleteLDAPTemplateBody
   */
  name?: string
  /**
   *
   * @type {string}
   * @memberof ApiLDAPDeleteLDAPTemplateBody
   */
  objclass?: string
  /**
   * default: 1
   * @type {number}
   * @memberof ApiLDAPDeleteLDAPTemplateBody
   */
  page?: number
  /**
   *
   * @type {string}
   * @memberof ApiLDAPDeleteLDAPTemplateBody
   */
  q?: string
  /**
   *
   * @type {number}
   * @memberof ApiLDAPDeleteLDAPTemplateBody
   */
  size?: number
  /**
   *
   * @type {Array<string>}
   * @memberof ApiLDAPDeleteLDAPTemplateBody
   */
  sort?: Array<string>
}
