// tslint:disable
/**
 * Webitel API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 24.04.0
 * Contact: support@webitel.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface ApiAccessToken
 */
export interface ApiAccessToken {
  /**
   * REQUIRED. The access token issued by the authorization server.
   * @type {string}
   * @memberof ApiAccessToken
   */
  access_token?: string
  /**
   * RECOMMENDED. The lifetime in seconds of the access token.
   * @type {number}
   * @memberof ApiAccessToken
   */
  expires_in?: number
  /**
   * OPTIONAL. The refresh token, which can be used to obtain new access tokens using the same authorization grant.
   * @type {string}
   * @memberof ApiAccessToken
   */
  refresh_token?: string
  /**
   * OPTIONAL, if identical to the scope requested by the client; otherwise, REQUIRED. The scope of the access token. repeated string scope = 5 [ json_name = \"scope\" ]; REQUIRED if the \"state\" parameter was present in the client authorization request. The exact value received from the client.
   * @type {string}
   * @memberof ApiAccessToken
   */
  state?: string
  /**
   * REQUIRED. The type of the token issued. Value is case insensitive.
   * @type {string}
   * @memberof ApiAccessToken
   */
  token_type?: string
}
