// tslint:disable
/**
 * Webitel API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 24.04.0
 * Contact: support@webitel.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ApiLicenseUser } from './api-license-user'
import { ApiVerification } from './api-verification'

/**
 *
 * @export
 * @interface ApiLicenseV1
 */
export interface ApiLicenseV1 {
  /**
   *
   * @type {boolean}
   * @memberof ApiLicenseV1
   */
  competitive?: boolean
  /**
   *
   * @type {string}
   * @memberof ApiLicenseV1
   */
  id?: string
  /**
   *
   * @type {number}
   * @memberof ApiLicenseV1
   */
  limit?: number
  /**
   *
   * @type {string}
   * @memberof ApiLicenseV1
   */
  not_after?: string
  /**
   *
   * @type {string}
   * @memberof ApiLicenseV1
   */
  not_before?: string
  /**
   *
   * @type {string}
   * @memberof ApiLicenseV1
   */
  product?: string
  /**
   * available
   * @type {number}
   * @memberof ApiLicenseV1
   */
  remain?: number
  /**
   * list of known classes, &this product grants mandatory access to, e.g.: \'users\', \'roles\', \'cc_agent\', \'calendars\', ...
   * @type {Array<string>}
   * @memberof ApiLicenseV1
   */
  scope?: Array<string>
  /**
   *
   * @type {ApiVerification}
   * @memberof ApiLicenseV1
   */
  status?: ApiVerification
  /**
   *
   * @type {Array<ApiLicenseUser>}
   * @memberof ApiLicenseV1
   */
  users?: Array<ApiLicenseUser>
}
