// tslint:disable
/**
 * Webitel API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 24.04.0
 * Contact: support@webitel.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CasesCaseCommentList } from './cases-case-comment-list'
import { CasesCaseFileList } from './cases-case-file-list'
import { CasesCaseLinkList } from './cases-case-link-list'
import { CasesCloseInfo } from './cases-close-info'
import { CasesRateInfo } from './cases-rate-info'
import { CasesRelatedCaseList } from './cases-related-case-list'
import { CasesSLACondition } from './cases-slacondition'
import { CasesSourceTypeLookup } from './cases-source-type-lookup'
import { CasesTimingInfo } from './cases-timing-info'
import { GeneralLookup } from './general-lookup'

/**
 * Message representing a case.
 * @export
 * @interface CasesCase
 */
export interface CasesCase {
  /**
   *
   * @type {GeneralLookup}
   * @memberof CasesCase
   */
  assignee?: GeneralLookup
  /**
   *
   * @type {GeneralLookup}
   * @memberof CasesCase
   */
  author?: GeneralLookup
  /**
   *
   * @type {CasesCloseInfo}
   * @memberof CasesCase
   */
  close?: CasesCloseInfo
  /**
   *
   * @type {GeneralLookup}
   * @memberof CasesCase
   */
  closeReasonGroup?: GeneralLookup
  /**
   *
   * @type {CasesCaseCommentList}
   * @memberof CasesCase
   */
  comments?: CasesCaseCommentList
  /**
   * Contact information for the case.
   * @type {string}
   * @memberof CasesCase
   */
  contactInfo?: string
  /**
   *
   * @type {string}
   * @memberof CasesCase
   */
  createdAt?: string
  /**
   *
   * @type {GeneralLookup}
   * @memberof CasesCase
   */
  createdBy?: GeneralLookup
  /**
   * Detailed description of the case.
   * @type {string}
   * @memberof CasesCase
   */
  description?: string
  /**
   *
   * @type {CasesCaseFileList}
   * @memberof CasesCase
   */
  files?: CasesCaseFileList
  /**
   *
   * @type {GeneralLookup}
   * @memberof CasesCase
   */
  group?: GeneralLookup
  /**
   *
   * @type {string}
   * @memberof CasesCase
   */
  id?: string
  /**
   *
   * @type {GeneralLookup}
   * @memberof CasesCase
   */
  impacted?: GeneralLookup
  /**
   *
   * @type {CasesCaseLinkList}
   * @memberof CasesCase
   */
  links?: CasesCaseLinkList
  /**
   * Name of the case (may serve as an ID in docs).
   * @type {string}
   * @memberof CasesCase
   */
  name?: string
  /**
   * Planned reaction time (in milliseconds).
   * @type {string}
   * @memberof CasesCase
   */
  plannedReactionAt?: string
  /**
   * Planned resolution time (in milliseconds).
   * @type {string}
   * @memberof CasesCase
   */
  plannedResolveAt?: string
  /**
   *
   * @type {GeneralLookup}
   * @memberof CasesCase
   */
  priority?: GeneralLookup
  /**
   *
   * @type {CasesRateInfo}
   * @memberof CasesCase
   */
  rate?: CasesRateInfo
  /**
   *
   * @type {CasesRelatedCaseList}
   * @memberof CasesCase
   */
  related?: CasesRelatedCaseList
  /**
   *
   * @type {GeneralLookup}
   * @memberof CasesCase
   */
  reporter?: GeneralLookup
  /**
   *
   * @type {GeneralLookup}
   * @memberof CasesCase
   */
  service?: GeneralLookup
  /**
   *
   * @type {GeneralLookup}
   * @memberof CasesCase
   */
  sla?: GeneralLookup
  /**
   * List of SLA conditions.
   * @type {Array<CasesSLACondition>}
   * @memberof CasesCase
   */
  slaCondition?: Array<CasesSLACondition>
  /**
   *
   * @type {CasesSourceTypeLookup}
   * @memberof CasesCase
   */
  source?: CasesSourceTypeLookup
  /**
   *
   * @type {GeneralLookup}
   * @memberof CasesCase
   */
  status?: GeneralLookup
  /**
   *
   * @type {GeneralLookup}
   * @memberof CasesCase
   */
  statusCondition?: GeneralLookup
  /**
   * Subject of the case.
   * @type {string}
   * @memberof CasesCase
   */
  subject?: string
  /**
   *
   * @type {CasesTimingInfo}
   * @memberof CasesCase
   */
  timing?: CasesTimingInfo
  /**
   *
   * @type {string}
   * @memberof CasesCase
   */
  updatedAt?: string
  /**
   *
   * @type {GeneralLookup}
   * @memberof CasesCase
   */
  updatedBy?: GeneralLookup
  /**
   *
   * @type {number}
   * @memberof CasesCase
   */
  ver?: number
}
