// tslint:disable
/**
 * Webitel API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 24.04.0
 * Contact: support@webitel.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GeneralLookup } from './general-lookup'

/**
 *
 * @export
 * @interface CasesInputCatalog
 */
export interface CasesInputCatalog {
  /**
   *
   * @type {GeneralLookup}
   * @memberof CasesInputCatalog
   */
  close_reason_group?: GeneralLookup
  /**
   *
   * @type {string}
   * @memberof CasesInputCatalog
   */
  code?: string
  /**
   *
   * @type {string}
   * @memberof CasesInputCatalog
   */
  description?: string
  /**
   *
   * @type {string}
   * @memberof CasesInputCatalog
   */
  name?: string
  /**
   *
   * @type {string}
   * @memberof CasesInputCatalog
   */
  prefix?: string
  /**
   *
   * @type {Array<GeneralLookup>}
   * @memberof CasesInputCatalog
   */
  skills?: Array<GeneralLookup>
  /**
   *
   * @type {GeneralLookup}
   * @memberof CasesInputCatalog
   */
  sla?: GeneralLookup
  /**
   *
   * @type {boolean}
   * @memberof CasesInputCatalog
   */
  state?: boolean
  /**
   *
   * @type {GeneralLookup}
   * @memberof CasesInputCatalog
   */
  status?: GeneralLookup
  /**
   *
   * @type {Array<GeneralLookup>}
   * @memberof CasesInputCatalog
   */
  teams?: Array<GeneralLookup>
}
