// tslint:disable
/**
 * Webitel API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 24.04.0
 * Contact: support@webitel.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GeneralLookup } from './general-lookup'
import { WebitelcasesType } from './webitelcases-type'

/**
 * Represents a source entity in the contact system.
 * @export
 * @interface CasesSource
 */
export interface CasesSource {
  /**
   *
   * @type {string}
   * @memberof CasesSource
   */
  createdAt?: string
  /**
   *
   * @type {GeneralLookup}
   * @memberof CasesSource
   */
  createdBy?: GeneralLookup
  /**
   *
   * @type {string}
   * @memberof CasesSource
   */
  description?: string
  /**
   *
   * @type {string}
   * @memberof CasesSource
   */
  id?: string
  /**
   *
   * @type {string}
   * @memberof CasesSource
   */
  name?: string
  /**
   *
   * @type {WebitelcasesType}
   * @memberof CasesSource
   */
  type?: WebitelcasesType
  /**
   *
   * @type {string}
   * @memberof CasesSource
   */
  updatedAt?: string
  /**
   *
   * @type {GeneralLookup}
   * @memberof CasesSource
   */
  updatedBy?: GeneralLookup
}
