// tslint:disable
/**
 * Webitel API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 24.04.0
 * Contact: support@webitel.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GeneralLookup } from './general-lookup'

/**
 *
 * @export
 * @interface CasesCaseLink
 */
export interface CasesCaseLink {
  /**
   *
   * @type {GeneralLookup}
   * @memberof CasesCaseLink
   */
  author?: GeneralLookup
  /**
   *
   * @type {string}
   * @memberof CasesCaseLink
   */
  createdAt?: string
  /**
   *
   * @type {GeneralLookup}
   * @memberof CasesCaseLink
   */
  createdBy?: GeneralLookup
  /**
   *
   * @type {string}
   * @memberof CasesCaseLink
   */
  id?: string
  /**
   *
   * @type {string}
   * @memberof CasesCaseLink
   */
  name?: string
  /**
   *
   * @type {string}
   * @memberof CasesCaseLink
   */
  updatedAt?: string
  /**
   *
   * @type {GeneralLookup}
   * @memberof CasesCaseLink
   */
  updatedBy?: GeneralLookup
  /**
   *
   * @type {string}
   * @memberof CasesCaseLink
   */
  url?: string
  /**
   *
   * @type {number}
   * @memberof CasesCaseLink
   */
  ver?: number
}
