// tslint:disable
/**
 * Webitel API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 24.04.0
 * Contact: support@webitel.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as globalImportUrl from 'url'
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios'
import { Configuration } from '../configuration'
// Some imports not used depending on template conditions
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  RequestArgs,
  BaseAPI,
  RequiredError,
} from '../base'
// @ts-ignore
import { CasesCloseReasonGroup } from '../api'
// @ts-ignore
import { CasesCloseReasonGroupList } from '../api'
// @ts-ignore
import { CasesCreateCloseReasonGroupRequest } from '../api'
// @ts-ignore
import { CasesInputCloseReasonGroup } from '../api'
// @ts-ignore
import { CasesLocateCloseReasonGroupResponse } from '../api'
// @ts-ignore
import { GooglerpcStatus } from '../api'
/**
 * CloseReasonGroupsApi - axios parameter creator
 * @export
 */
export const CloseReasonGroupsApiAxiosParamCreator = function(
  configuration?: Configuration
) {
  return {
    /**
     *
     * @summary Create a new close reason group
     * @param {CasesCreateCloseReasonGroupRequest} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createCloseReasonGroup: async (
      body: CasesCreateCloseReasonGroupRequest,
      options: any = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'body' is not null or undefined
      if (body === null || body === undefined) {
        throw new RequiredError(
          'body',
          'Required parameter body was null or undefined when calling createCloseReasonGroup.'
        )
      }
      const localVarPath = `/cases/close_reason_groups`
      const localVarUrlObj = globalImportUrl.parse(localVarPath, true)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }
      const localVarRequestOptions = {
        method: 'POST',
        ...baseOptions,
        ...options,
      }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication AccessToken required
      if (configuration && configuration.apiKey) {
        const localVarApiKeyValue =
          typeof configuration.apiKey === 'function'
            ? await configuration.apiKey('X-Webitel-Access')
            : await configuration.apiKey
        localVarHeaderParameter['X-Webitel-Access'] = localVarApiKeyValue
      }

      localVarHeaderParameter['Content-Type'] = 'application/json'

      localVarUrlObj.query = {
        ...localVarUrlObj.query,
        ...localVarQueryParameter,
        ...options.query,
      }
      // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
      delete localVarUrlObj.search
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      }
      const needsSerialization =
        typeof body !== 'string' ||
        localVarRequestOptions.headers['Content-Type'] === 'application/json'
      localVarRequestOptions.data = needsSerialization
        ? JSON.stringify(body !== undefined ? body : {})
        : body || ''

      return {
        url: globalImportUrl.format(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     *
     * @summary Delete a close reason group
     * @param {string} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteCloseReasonGroup: async (
      id: string,
      options: any = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      if (id === null || id === undefined) {
        throw new RequiredError(
          'id',
          'Required parameter id was null or undefined when calling deleteCloseReasonGroup.'
        )
      }
      const localVarPath = `/cases/close_reason_groups/{id}`.replace(
        `{${'id'}}`,
        encodeURIComponent(String(id))
      )
      const localVarUrlObj = globalImportUrl.parse(localVarPath, true)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }
      const localVarRequestOptions = {
        method: 'DELETE',
        ...baseOptions,
        ...options,
      }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication AccessToken required
      if (configuration && configuration.apiKey) {
        const localVarApiKeyValue =
          typeof configuration.apiKey === 'function'
            ? await configuration.apiKey('X-Webitel-Access')
            : await configuration.apiKey
        localVarHeaderParameter['X-Webitel-Access'] = localVarApiKeyValue
      }

      localVarUrlObj.query = {
        ...localVarUrlObj.query,
        ...localVarQueryParameter,
        ...options.query,
      }
      // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
      delete localVarUrlObj.search
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      }

      return {
        url: globalImportUrl.format(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     *
     * @summary Retrieve a list of close reason groups or search close reason groups
     * @param {number} [page]
     * @param {number} [size]
     * @param {Array<string>} [fields]
     * @param {Array<string>} [sort]
     * @param {Array<string>} [id]
     * @param {string} [q]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listCloseReasonGroups: async (
      page?: number,
      size?: number,
      fields?: Array<string>,
      sort?: Array<string>,
      id?: Array<string>,
      q?: string,
      options: any = {}
    ): Promise<RequestArgs> => {
      const localVarPath = `/cases/close_reason_groups`
      const localVarUrlObj = globalImportUrl.parse(localVarPath, true)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }
      const localVarRequestOptions = {
        method: 'GET',
        ...baseOptions,
        ...options,
      }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication AccessToken required
      if (configuration && configuration.apiKey) {
        const localVarApiKeyValue =
          typeof configuration.apiKey === 'function'
            ? await configuration.apiKey('X-Webitel-Access')
            : await configuration.apiKey
        localVarHeaderParameter['X-Webitel-Access'] = localVarApiKeyValue
      }

      if (page !== undefined) {
        localVarQueryParameter['page'] = page
      }

      if (size !== undefined) {
        localVarQueryParameter['size'] = size
      }

      if (fields) {
        localVarQueryParameter['fields'] = fields
      }

      if (sort) {
        localVarQueryParameter['sort'] = sort
      }

      if (id) {
        localVarQueryParameter['id'] = id
      }

      if (q !== undefined) {
        localVarQueryParameter['q'] = q
      }

      localVarUrlObj.query = {
        ...localVarUrlObj.query,
        ...localVarQueryParameter,
        ...options.query,
      }
      // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
      delete localVarUrlObj.search
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      }

      return {
        url: globalImportUrl.format(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     *
     * @summary Locate a close reason group by ID
     * @param {string} id
     * @param {Array<string>} [fields]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    locateCloseReasonGroup: async (
      id: string,
      fields?: Array<string>,
      options: any = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      if (id === null || id === undefined) {
        throw new RequiredError(
          'id',
          'Required parameter id was null or undefined when calling locateCloseReasonGroup.'
        )
      }
      const localVarPath = `/cases/close_reason_groups/{id}`.replace(
        `{${'id'}}`,
        encodeURIComponent(String(id))
      )
      const localVarUrlObj = globalImportUrl.parse(localVarPath, true)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }
      const localVarRequestOptions = {
        method: 'GET',
        ...baseOptions,
        ...options,
      }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication AccessToken required
      if (configuration && configuration.apiKey) {
        const localVarApiKeyValue =
          typeof configuration.apiKey === 'function'
            ? await configuration.apiKey('X-Webitel-Access')
            : await configuration.apiKey
        localVarHeaderParameter['X-Webitel-Access'] = localVarApiKeyValue
      }

      if (fields) {
        localVarQueryParameter['fields'] = fields
      }

      localVarUrlObj.query = {
        ...localVarUrlObj.query,
        ...localVarQueryParameter,
        ...options.query,
      }
      // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
      delete localVarUrlObj.search
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      }

      return {
        url: globalImportUrl.format(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     *
     * @summary Update an existing close reason group
     * @param {string} id
     * @param {CasesInputCloseReasonGroup} input
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateCloseReasonGroup: async (
      id: string,
      input: CasesInputCloseReasonGroup,
      options: any = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      if (id === null || id === undefined) {
        throw new RequiredError(
          'id',
          'Required parameter id was null or undefined when calling updateCloseReasonGroup.'
        )
      }
      // verify required parameter 'input' is not null or undefined
      if (input === null || input === undefined) {
        throw new RequiredError(
          'input',
          'Required parameter input was null or undefined when calling updateCloseReasonGroup.'
        )
      }
      const localVarPath = `/cases/close_reason_groups/{id}`.replace(
        `{${'id'}}`,
        encodeURIComponent(String(id))
      )
      const localVarUrlObj = globalImportUrl.parse(localVarPath, true)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }
      const localVarRequestOptions = {
        method: 'PUT',
        ...baseOptions,
        ...options,
      }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication AccessToken required
      if (configuration && configuration.apiKey) {
        const localVarApiKeyValue =
          typeof configuration.apiKey === 'function'
            ? await configuration.apiKey('X-Webitel-Access')
            : await configuration.apiKey
        localVarHeaderParameter['X-Webitel-Access'] = localVarApiKeyValue
      }

      localVarHeaderParameter['Content-Type'] = 'application/json'

      localVarUrlObj.query = {
        ...localVarUrlObj.query,
        ...localVarQueryParameter,
        ...options.query,
      }
      // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
      delete localVarUrlObj.search
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      }
      const needsSerialization =
        typeof input !== 'string' ||
        localVarRequestOptions.headers['Content-Type'] === 'application/json'
      localVarRequestOptions.data = needsSerialization
        ? JSON.stringify(input !== undefined ? input : {})
        : input || ''

      return {
        url: globalImportUrl.format(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     *
     * @summary Update an existing close reason group
     * @param {string} id
     * @param {CasesInputCloseReasonGroup} input
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateCloseReasonGroup2: async (
      id: string,
      input: CasesInputCloseReasonGroup,
      options: any = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      if (id === null || id === undefined) {
        throw new RequiredError(
          'id',
          'Required parameter id was null or undefined when calling updateCloseReasonGroup2.'
        )
      }
      // verify required parameter 'input' is not null or undefined
      if (input === null || input === undefined) {
        throw new RequiredError(
          'input',
          'Required parameter input was null or undefined when calling updateCloseReasonGroup2.'
        )
      }
      const localVarPath = `/cases/close_reason_groups/{id}`.replace(
        `{${'id'}}`,
        encodeURIComponent(String(id))
      )
      const localVarUrlObj = globalImportUrl.parse(localVarPath, true)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }
      const localVarRequestOptions = {
        method: 'PATCH',
        ...baseOptions,
        ...options,
      }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication AccessToken required
      if (configuration && configuration.apiKey) {
        const localVarApiKeyValue =
          typeof configuration.apiKey === 'function'
            ? await configuration.apiKey('X-Webitel-Access')
            : await configuration.apiKey
        localVarHeaderParameter['X-Webitel-Access'] = localVarApiKeyValue
      }

      localVarHeaderParameter['Content-Type'] = 'application/json'

      localVarUrlObj.query = {
        ...localVarUrlObj.query,
        ...localVarQueryParameter,
        ...options.query,
      }
      // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
      delete localVarUrlObj.search
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      }
      const needsSerialization =
        typeof input !== 'string' ||
        localVarRequestOptions.headers['Content-Type'] === 'application/json'
      localVarRequestOptions.data = needsSerialization
        ? JSON.stringify(input !== undefined ? input : {})
        : input || ''

      return {
        url: globalImportUrl.format(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
  }
}

/**
 * CloseReasonGroupsApi - functional programming interface
 * @export
 */
export const CloseReasonGroupsApiFp = function(configuration?: Configuration) {
  return {
    /**
     *
     * @summary Create a new close reason group
     * @param {CasesCreateCloseReasonGroupRequest} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async createCloseReasonGroup(
      body: CasesCreateCloseReasonGroupRequest,
      options?: any
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string
      ) => AxiosPromise<CasesCloseReasonGroup>
    > {
      const localVarAxiosArgs = await CloseReasonGroupsApiAxiosParamCreator(
        configuration
      ).createCloseReasonGroup(body, options)
      return (
        axios: AxiosInstance = globalAxios,
        basePath: string = BASE_PATH
      ) => {
        const axiosRequestArgs = {
          ...localVarAxiosArgs.options,
          url: basePath + localVarAxiosArgs.url,
        }
        return axios.request(axiosRequestArgs)
      }
    },
    /**
     *
     * @summary Delete a close reason group
     * @param {string} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async deleteCloseReasonGroup(
      id: string,
      options?: any
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string
      ) => AxiosPromise<CasesCloseReasonGroup>
    > {
      const localVarAxiosArgs = await CloseReasonGroupsApiAxiosParamCreator(
        configuration
      ).deleteCloseReasonGroup(id, options)
      return (
        axios: AxiosInstance = globalAxios,
        basePath: string = BASE_PATH
      ) => {
        const axiosRequestArgs = {
          ...localVarAxiosArgs.options,
          url: basePath + localVarAxiosArgs.url,
        }
        return axios.request(axiosRequestArgs)
      }
    },
    /**
     *
     * @summary Retrieve a list of close reason groups or search close reason groups
     * @param {number} [page]
     * @param {number} [size]
     * @param {Array<string>} [fields]
     * @param {Array<string>} [sort]
     * @param {Array<string>} [id]
     * @param {string} [q]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async listCloseReasonGroups(
      page?: number,
      size?: number,
      fields?: Array<string>,
      sort?: Array<string>,
      id?: Array<string>,
      q?: string,
      options?: any
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string
      ) => AxiosPromise<CasesCloseReasonGroupList>
    > {
      const localVarAxiosArgs = await CloseReasonGroupsApiAxiosParamCreator(
        configuration
      ).listCloseReasonGroups(page, size, fields, sort, id, q, options)
      return (
        axios: AxiosInstance = globalAxios,
        basePath: string = BASE_PATH
      ) => {
        const axiosRequestArgs = {
          ...localVarAxiosArgs.options,
          url: basePath + localVarAxiosArgs.url,
        }
        return axios.request(axiosRequestArgs)
      }
    },
    /**
     *
     * @summary Locate a close reason group by ID
     * @param {string} id
     * @param {Array<string>} [fields]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async locateCloseReasonGroup(
      id: string,
      fields?: Array<string>,
      options?: any
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string
      ) => AxiosPromise<CasesLocateCloseReasonGroupResponse>
    > {
      const localVarAxiosArgs = await CloseReasonGroupsApiAxiosParamCreator(
        configuration
      ).locateCloseReasonGroup(id, fields, options)
      return (
        axios: AxiosInstance = globalAxios,
        basePath: string = BASE_PATH
      ) => {
        const axiosRequestArgs = {
          ...localVarAxiosArgs.options,
          url: basePath + localVarAxiosArgs.url,
        }
        return axios.request(axiosRequestArgs)
      }
    },
    /**
     *
     * @summary Update an existing close reason group
     * @param {string} id
     * @param {CasesInputCloseReasonGroup} input
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async updateCloseReasonGroup(
      id: string,
      input: CasesInputCloseReasonGroup,
      options?: any
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string
      ) => AxiosPromise<CasesCloseReasonGroup>
    > {
      const localVarAxiosArgs = await CloseReasonGroupsApiAxiosParamCreator(
        configuration
      ).updateCloseReasonGroup(id, input, options)
      return (
        axios: AxiosInstance = globalAxios,
        basePath: string = BASE_PATH
      ) => {
        const axiosRequestArgs = {
          ...localVarAxiosArgs.options,
          url: basePath + localVarAxiosArgs.url,
        }
        return axios.request(axiosRequestArgs)
      }
    },
    /**
     *
     * @summary Update an existing close reason group
     * @param {string} id
     * @param {CasesInputCloseReasonGroup} input
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async updateCloseReasonGroup2(
      id: string,
      input: CasesInputCloseReasonGroup,
      options?: any
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string
      ) => AxiosPromise<CasesCloseReasonGroup>
    > {
      const localVarAxiosArgs = await CloseReasonGroupsApiAxiosParamCreator(
        configuration
      ).updateCloseReasonGroup2(id, input, options)
      return (
        axios: AxiosInstance = globalAxios,
        basePath: string = BASE_PATH
      ) => {
        const axiosRequestArgs = {
          ...localVarAxiosArgs.options,
          url: basePath + localVarAxiosArgs.url,
        }
        return axios.request(axiosRequestArgs)
      }
    },
  }
}

/**
 * CloseReasonGroupsApi - factory interface
 * @export
 */
export const CloseReasonGroupsApiFactory = function(
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance
) {
  return {
    /**
     *
     * @summary Create a new close reason group
     * @param {CasesCreateCloseReasonGroupRequest} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createCloseReasonGroup(
      body: CasesCreateCloseReasonGroupRequest,
      options?: any
    ): AxiosPromise<CasesCloseReasonGroup> {
      return CloseReasonGroupsApiFp(configuration)
        .createCloseReasonGroup(body, options)
        .then((request) => request(axios, basePath))
    },
    /**
     *
     * @summary Delete a close reason group
     * @param {string} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteCloseReasonGroup(
      id: string,
      options?: any
    ): AxiosPromise<CasesCloseReasonGroup> {
      return CloseReasonGroupsApiFp(configuration)
        .deleteCloseReasonGroup(id, options)
        .then((request) => request(axios, basePath))
    },
    /**
     *
     * @summary Retrieve a list of close reason groups or search close reason groups
     * @param {number} [page]
     * @param {number} [size]
     * @param {Array<string>} [fields]
     * @param {Array<string>} [sort]
     * @param {Array<string>} [id]
     * @param {string} [q]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listCloseReasonGroups(
      page?: number,
      size?: number,
      fields?: Array<string>,
      sort?: Array<string>,
      id?: Array<string>,
      q?: string,
      options?: any
    ): AxiosPromise<CasesCloseReasonGroupList> {
      return CloseReasonGroupsApiFp(configuration)
        .listCloseReasonGroups(page, size, fields, sort, id, q, options)
        .then((request) => request(axios, basePath))
    },
    /**
     *
     * @summary Locate a close reason group by ID
     * @param {string} id
     * @param {Array<string>} [fields]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    locateCloseReasonGroup(
      id: string,
      fields?: Array<string>,
      options?: any
    ): AxiosPromise<CasesLocateCloseReasonGroupResponse> {
      return CloseReasonGroupsApiFp(configuration)
        .locateCloseReasonGroup(id, fields, options)
        .then((request) => request(axios, basePath))
    },
    /**
     *
     * @summary Update an existing close reason group
     * @param {string} id
     * @param {CasesInputCloseReasonGroup} input
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateCloseReasonGroup(
      id: string,
      input: CasesInputCloseReasonGroup,
      options?: any
    ): AxiosPromise<CasesCloseReasonGroup> {
      return CloseReasonGroupsApiFp(configuration)
        .updateCloseReasonGroup(id, input, options)
        .then((request) => request(axios, basePath))
    },
    /**
     *
     * @summary Update an existing close reason group
     * @param {string} id
     * @param {CasesInputCloseReasonGroup} input
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateCloseReasonGroup2(
      id: string,
      input: CasesInputCloseReasonGroup,
      options?: any
    ): AxiosPromise<CasesCloseReasonGroup> {
      return CloseReasonGroupsApiFp(configuration)
        .updateCloseReasonGroup2(id, input, options)
        .then((request) => request(axios, basePath))
    },
  }
}

/**
 * CloseReasonGroupsApi - object-oriented interface
 * @export
 * @class CloseReasonGroupsApi
 * @extends {BaseAPI}
 */
export class CloseReasonGroupsApi extends BaseAPI {
  /**
   *
   * @summary Create a new close reason group
   * @param {CasesCreateCloseReasonGroupRequest} body
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof CloseReasonGroupsApi
   */
  public createCloseReasonGroup(
    body: CasesCreateCloseReasonGroupRequest,
    options?: any
  ) {
    return CloseReasonGroupsApiFp(this.configuration)
      .createCloseReasonGroup(body, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   *
   * @summary Delete a close reason group
   * @param {string} id
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof CloseReasonGroupsApi
   */
  public deleteCloseReasonGroup(id: string, options?: any) {
    return CloseReasonGroupsApiFp(this.configuration)
      .deleteCloseReasonGroup(id, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   *
   * @summary Retrieve a list of close reason groups or search close reason groups
   * @param {number} [page]
   * @param {number} [size]
   * @param {Array<string>} [fields]
   * @param {Array<string>} [sort]
   * @param {Array<string>} [id]
   * @param {string} [q]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof CloseReasonGroupsApi
   */
  public listCloseReasonGroups(
    page?: number,
    size?: number,
    fields?: Array<string>,
    sort?: Array<string>,
    id?: Array<string>,
    q?: string,
    options?: any
  ) {
    return CloseReasonGroupsApiFp(this.configuration)
      .listCloseReasonGroups(page, size, fields, sort, id, q, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   *
   * @summary Locate a close reason group by ID
   * @param {string} id
   * @param {Array<string>} [fields]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof CloseReasonGroupsApi
   */
  public locateCloseReasonGroup(
    id: string,
    fields?: Array<string>,
    options?: any
  ) {
    return CloseReasonGroupsApiFp(this.configuration)
      .locateCloseReasonGroup(id, fields, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   *
   * @summary Update an existing close reason group
   * @param {string} id
   * @param {CasesInputCloseReasonGroup} input
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof CloseReasonGroupsApi
   */
  public updateCloseReasonGroup(
    id: string,
    input: CasesInputCloseReasonGroup,
    options?: any
  ) {
    return CloseReasonGroupsApiFp(this.configuration)
      .updateCloseReasonGroup(id, input, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   *
   * @summary Update an existing close reason group
   * @param {string} id
   * @param {CasesInputCloseReasonGroup} input
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof CloseReasonGroupsApi
   */
  public updateCloseReasonGroup2(
    id: string,
    input: CasesInputCloseReasonGroup,
    options?: any
  ) {
    return CloseReasonGroupsApiFp(this.configuration)
      .updateCloseReasonGroup2(id, input, options)
      .then((request) => request(this.axios, this.basePath))
  }
}
