// tslint:disable
/**
 * Webitel API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 23.09.0
 * Contact: support@webitel.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EngineLookup } from './engine-lookup'

/**
 *
 * @export
 * @interface EngineMemberAttempt
 */
export interface EngineMemberAttempt {
  /**
   *
   * @type {boolean}
   * @memberof EngineMemberAttempt
   */
  active?: boolean
  /**
   *
   * @type {EngineLookup}
   * @memberof EngineMemberAttempt
   */
  agent?: EngineLookup
  /**
   *
   * @type {string}
   * @memberof EngineMemberAttempt
   */
  answered_at?: string
  /**
   *
   * @type {number}
   * @memberof EngineMemberAttempt
   */
  attempts?: number
  /**
   *
   * @type {string}
   * @memberof EngineMemberAttempt
   */
  bridged_at?: string
  /**
   *
   * @type {EngineLookup}
   * @memberof EngineMemberAttempt
   */
  bucket?: EngineLookup
  /**
   *
   * @type {string}
   * @memberof EngineMemberAttempt
   */
  created_at?: string
  /**
   *
   * @type {string}
   * @memberof EngineMemberAttempt
   */
  destination?: string
  /**
   *
   * @type {string}
   * @memberof EngineMemberAttempt
   */
  hangup_at?: string
  /**
   *
   * @type {string}
   * @memberof EngineMemberAttempt
   */
  id?: string
  /**
   *
   * @type {string}
   * @memberof EngineMemberAttempt
   */
  leg_a_id?: string
  /**
   *
   * @type {string}
   * @memberof EngineMemberAttempt
   */
  leg_b_id?: string
  /**
   *
   * @type {object}
   * @memberof EngineMemberAttempt
   */
  logs?: object
  /**
   *
   * @type {EngineLookup}
   * @memberof EngineMemberAttempt
   */
  member?: EngineLookup
  /**
   *
   * @type {string}
   * @memberof EngineMemberAttempt
   */
  node?: string
  /**
   *
   * @type {string}
   * @memberof EngineMemberAttempt
   */
  originate_at?: string
  /**
   *
   * @type {EngineLookup}
   * @memberof EngineMemberAttempt
   */
  resource?: EngineLookup
  /**
   *
   * @type {string}
   * @memberof EngineMemberAttempt
   */
  result?: string
  /**
   *
   * @type {number}
   * @memberof EngineMemberAttempt
   */
  weight?: number
}
