// tslint:disable
/**
 * Webitel API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 24.04.0
 * Contact: support@webitel.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Media File.
 * @export
 * @interface EngineBroadcastFile
 */
export interface EngineBroadcastFile {
  /**
   *
   * @type {string}
   * @memberof EngineBroadcastFile
   */
  id?: string
  /**
   *
   * @type {string}
   * @memberof EngineBroadcastFile
   */
  mime?: string
  /**
   *
   * @type {string}
   * @memberof EngineBroadcastFile
   */
  name?: string
  /**
   *
   * @type {string}
   * @memberof EngineBroadcastFile
   */
  size?: string
  /**
   *
   * @type {string}
   * @memberof EngineBroadcastFile
   */
  url?: string
}
