// tslint:disable
/**
 * Webitel API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 24.04.0
 * Contact: support@webitel.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EngineLookup } from './engine-lookup'

/**
 *
 * @export
 * @interface EngineAgentTeamServiceUpdateAgentTeamBody
 */
export interface EngineAgentTeamServiceUpdateAgentTeamBody {
  /**
   *
   * @type {Array<EngineLookup>}
   * @memberof EngineAgentTeamServiceUpdateAgentTeamBody
   */
  admin?: Array<EngineLookup>
  /**
   *
   * @type {number}
   * @memberof EngineAgentTeamServiceUpdateAgentTeamBody
   */
  call_timeout?: number
  /**
   *
   * @type {string}
   * @memberof EngineAgentTeamServiceUpdateAgentTeamBody
   */
  description?: string
  /**
   *
   * @type {string}
   * @memberof EngineAgentTeamServiceUpdateAgentTeamBody
   */
  domain_id?: string
  /**
   *
   * @type {EngineLookup}
   * @memberof EngineAgentTeamServiceUpdateAgentTeamBody
   */
  forecast_calculation?: EngineLookup
  /**
   *
   * @type {number}
   * @memberof EngineAgentTeamServiceUpdateAgentTeamBody
   */
  invite_chat_timeout?: number
  /**
   *
   * @type {number}
   * @memberof EngineAgentTeamServiceUpdateAgentTeamBody
   */
  max_no_answer?: number
  /**
   *
   * @type {string}
   * @memberof EngineAgentTeamServiceUpdateAgentTeamBody
   */
  name?: string
  /**
   *
   * @type {number}
   * @memberof EngineAgentTeamServiceUpdateAgentTeamBody
   */
  no_answer_delay_time?: number
  /**
   *
   * @type {string}
   * @memberof EngineAgentTeamServiceUpdateAgentTeamBody
   */
  strategy?: string
  /**
   *
   * @type {number}
   * @memberof EngineAgentTeamServiceUpdateAgentTeamBody
   */
  task_accept_timeout?: number
  /**
   *
   * @type {number}
   * @memberof EngineAgentTeamServiceUpdateAgentTeamBody
   */
  wrap_up_time?: number
}
