// tslint:disable
/**
 * Webitel API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 24.04.0
 * Contact: support@webitel.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface EngineCreateCallRequestCallSettings
 */
export interface EngineCreateCallRequestCallSettings {
  /**
   *
   * @type {boolean}
   * @memberof EngineCreateCallRequestCallSettings
   */
  audio?: boolean
  /**
   *
   * @type {boolean}
   * @memberof EngineCreateCallRequestCallSettings
   */
  cancel_distribute?: boolean
  /**
   *
   * @type {boolean}
   * @memberof EngineCreateCallRequestCallSettings
   */
  disable_auto_answer?: boolean
  /**
   *
   * @type {boolean}
   * @memberof EngineCreateCallRequestCallSettings
   */
  disable_stun?: boolean
  /**
   *
   * @type {string}
   * @memberof EngineCreateCallRequestCallSettings
   */
  display?: string
  /**
   *
   * @type {boolean}
   * @memberof EngineCreateCallRequestCallSettings
   */
  hide_number?: boolean
  /**
   *
   * @type {boolean}
   * @memberof EngineCreateCallRequestCallSettings
   */
  is_online?: boolean
  /**
   *
   * @type {boolean}
   * @memberof EngineCreateCallRequestCallSettings
   */
  record?: boolean
  /**
   *
   * @type {boolean}
   * @memberof EngineCreateCallRequestCallSettings
   */
  screen?: boolean
  /**
   *
   * @type {number}
   * @memberof EngineCreateCallRequestCallSettings
   */
  timeout?: number
  /**
   *
   * @type {{ [key: string]: string; }}
   * @memberof EngineCreateCallRequestCallSettings
   */
  variables?: { [key: string]: string }
  /**
   *
   * @type {boolean}
   * @memberof EngineCreateCallRequestCallSettings
   */
  video?: boolean
}
