// tslint:disable
/**
 * Webitel API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 24.04.0
 * Contact: support@webitel.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface EngineMemberServiceAttemptCallbackBody
 */
export interface EngineMemberServiceAttemptCallbackBody {
  /**
   *
   * @type {number}
   * @memberof EngineMemberServiceAttemptCallbackBody
   */
  agentId?: number
  /**
   *
   * @type {string}
   * @memberof EngineMemberServiceAttemptCallbackBody
   */
  description?: string
  /**
   *
   * @type {boolean}
   * @memberof EngineMemberServiceAttemptCallbackBody
   */
  display?: boolean
  /**
   *
   * @type {boolean}
   * @memberof EngineMemberServiceAttemptCallbackBody
   */
  excludeCurrentCommunication?: boolean
  /**
   *
   * @type {string}
   * @memberof EngineMemberServiceAttemptCallbackBody
   */
  expireAt?: string
  /**
   *
   * @type {string}
   * @memberof EngineMemberServiceAttemptCallbackBody
   */
  minOfferingAt?: string
  /**
   *
   * @type {boolean}
   * @memberof EngineMemberServiceAttemptCallbackBody
   */
  onlyCurrentCommunication?: boolean
  /**
   *
   * @type {string}
   * @memberof EngineMemberServiceAttemptCallbackBody
   */
  status?: string
  /**
   *
   * @type {{ [key: string]: string; }}
   * @memberof EngineMemberServiceAttemptCallbackBody
   */
  variables?: { [key: string]: string }
  /**
   *
   * @type {number}
   * @memberof EngineMemberServiceAttemptCallbackBody
   */
  waitBetweenRetries?: number
}
