// tslint:disable
/**
 * Webitel API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 24.04.0
 * Contact: support@webitel.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface EngineCreateQuickReplyRequest
 */
export interface EngineCreateQuickReplyRequest {
  /**
   *
   * @type {string}
   * @memberof EngineCreateQuickReplyRequest
   */
  article?: string
  /**
   *
   * @type {string}
   * @memberof EngineCreateQuickReplyRequest
   */
  name?: string
  /**
   *
   * @type {number}
   * @memberof EngineCreateQuickReplyRequest
   */
  queue?: number
  /**
   *
   * @type {string}
   * @memberof EngineCreateQuickReplyRequest
   */
  team?: string
  /**
   *
   * @type {string}
   * @memberof EngineCreateQuickReplyRequest
   */
  text?: string
}
