// tslint:disable
/**
 * Webitel API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 23.12.0
 * Contact: support@webitel.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface EngineCallHold
 */
export interface EngineCallHold {
  /**
   *
   * @type {number}
   * @memberof EngineCallHold
   */
  sec?: number
  /**
   *
   * @type {string}
   * @memberof EngineCallHold
   */
  start?: string
  /**
   *
   * @type {string}
   * @memberof EngineCallHold
   */
  stop?: string
}
