// tslint:disable
/**
 * Webitel engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 23.07.0
 * Contact: support@webitel.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface EngineUpdateOutboundResourceDisplayRequest
 */
export interface EngineUpdateOutboundResourceDisplayRequest {
  /**
   *
   * @type {string}
   * @memberof EngineUpdateOutboundResourceDisplayRequest
   */
  display?: string
  /**
   *
   * @type {string}
   * @memberof EngineUpdateOutboundResourceDisplayRequest
   */
  domain_id?: string
  /**
   *
   * @type {string}
   * @memberof EngineUpdateOutboundResourceDisplayRequest
   */
  id?: string
  /**
   *
   * @type {string}
   * @memberof EngineUpdateOutboundResourceDisplayRequest
   */
  resource_id?: string
}
