// tslint:disable
/**
 * Webitel API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 24.04.0
 * Contact: support@webitel.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EngineLookup } from './engine-lookup'

/**
 *
 * @export
 * @interface EngineAgentServicePatchAgentBody
 */
export interface EngineAgentServicePatchAgentBody {
  /**
   *
   * @type {Array<string>}
   * @memberof EngineAgentServicePatchAgentBody
   */
  allow_channels?: Array<string>
  /**
   *
   * @type {Array<EngineLookup>}
   * @memberof EngineAgentServicePatchAgentBody
   */
  auditor?: Array<EngineLookup>
  /**
   *
   * @type {number}
   * @memberof EngineAgentServicePatchAgentBody
   */
  chat_count?: number
  /**
   *
   * @type {string}
   * @memberof EngineAgentServicePatchAgentBody
   */
  description?: string
  /**
   *
   * @type {Array<string>}
   * @memberof EngineAgentServicePatchAgentBody
   */
  fields?: Array<string>
  /**
   *
   * @type {EngineLookup}
   * @memberof EngineAgentServicePatchAgentBody
   */
  greeting_media?: EngineLookup
  /**
   *
   * @type {boolean}
   * @memberof EngineAgentServicePatchAgentBody
   */
  is_supervisor?: boolean
  /**
   *
   * @type {number}
   * @memberof EngineAgentServicePatchAgentBody
   */
  progressive_count?: number
  /**
   *
   * @type {EngineLookup}
   * @memberof EngineAgentServicePatchAgentBody
   */
  region?: EngineLookup
  /**
   *
   * @type {Array<EngineLookup>}
   * @memberof EngineAgentServicePatchAgentBody
   */
  supervisor?: Array<EngineLookup>
  /**
   *
   * @type {EngineLookup}
   * @memberof EngineAgentServicePatchAgentBody
   */
  team?: EngineLookup
  /**
   *
   * @type {EngineLookup}
   * @memberof EngineAgentServicePatchAgentBody
   */
  user?: EngineLookup
}
