// tslint:disable
/**
 * Webitel API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 24.04.0
 * Contact: support@webitel.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EngineCommunicationChannels } from './engine-communication-channels'

/**
 *
 * @export
 * @interface EngineCommunicationTypeServicePatchCommunicationTypeBody
 */
export interface EngineCommunicationTypeServicePatchCommunicationTypeBody {
  /**
   *
   * @type {EngineCommunicationChannels}
   * @memberof EngineCommunicationTypeServicePatchCommunicationTypeBody
   */
  channel?: EngineCommunicationChannels
  /**
   *
   * @type {string}
   * @memberof EngineCommunicationTypeServicePatchCommunicationTypeBody
   */
  code?: string
  /**
   *
   * @type {boolean}
   * @memberof EngineCommunicationTypeServicePatchCommunicationTypeBody
   */
  _default?: boolean
  /**
   *
   * @type {string}
   * @memberof EngineCommunicationTypeServicePatchCommunicationTypeBody
   */
  description?: string
  /**
   *
   * @type {Array<string>}
   * @memberof EngineCommunicationTypeServicePatchCommunicationTypeBody
   */
  fields?: Array<string>
  /**
   *
   * @type {string}
   * @memberof EngineCommunicationTypeServicePatchCommunicationTypeBody
   */
  name?: string
}
