// tslint:disable
/**
 * Webitel engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2019.0.0
 * Contact: support@webitel.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { EngineLookup } from './engine-lookup'

/**
 *
 * @export
 * @interface EngineResourceTeamAgent
 */
export interface EngineResourceTeamAgent {
  /**
   *
   * @type {EngineLookup}
   * @memberof EngineResourceTeamAgent
   */
  agent?: EngineLookup
  /**
   *
   * @type {Array<EngineLookup>}
   * @memberof EngineResourceTeamAgent
   */
  buckets?: Array<EngineLookup>
  /**
   *
   * @type {string}
   * @memberof EngineResourceTeamAgent
   */
  id?: string
  /**
   *
   * @type {number}
   * @memberof EngineResourceTeamAgent
   */
  lvl?: number
  /**
   *
   * @type {string}
   * @memberof EngineResourceTeamAgent
   */
  team_id?: string
}
