// tslint:disable
/**
 * Webitel engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 20.12.0
 * Contact: support@webitel.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface EngineQueueRouting
 */
export interface EngineQueueRouting {
  /**
   *
   * @type {boolean}
   * @memberof EngineQueueRouting
   */
  disabled?: boolean
  /**
   *
   * @type {string}
   * @memberof EngineQueueRouting
   */
  id?: string
  /**
   *
   * @type {string}
   * @memberof EngineQueueRouting
   */
  pattern?: string
  /**
   *
   * @type {number}
   * @memberof EngineQueueRouting
   */
  priority?: number
  /**
   *
   * @type {string}
   * @memberof EngineQueueRouting
   */
  queue_id?: string
}
