// tslint:disable
/**
 * Webitel API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 24.04.0
 * Contact: support@webitel.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { GoogleProtobufAny } from './google-protobuf-any'

/**
 *
 * @export
 * @interface GrpcGatewayRuntimeStreamError
 */
export interface GrpcGatewayRuntimeStreamError {
  /**
   *
   * @type {Array<GoogleProtobufAny>}
   * @memberof GrpcGatewayRuntimeStreamError
   */
  details?: Array<GoogleProtobufAny>
  /**
   *
   * @type {number}
   * @memberof GrpcGatewayRuntimeStreamError
   */
  grpc_code?: number
  /**
   *
   * @type {number}
   * @memberof GrpcGatewayRuntimeStreamError
   */
  http_code?: number
  /**
   *
   * @type {string}
   * @memberof GrpcGatewayRuntimeStreamError
   */
  http_status?: string
  /**
   *
   * @type {string}
   * @memberof GrpcGatewayRuntimeStreamError
   */
  message?: string
}
