// tslint:disable
/**
 * Webitel engine API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 23.07.0
 * Contact: support@webitel.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface LoggerInsertConfigRequest
 */
export interface LoggerInsertConfigRequest {
  /**
   *
   * @type {number}
   * @memberof LoggerInsertConfigRequest
   */
  days_to_store?: number
  /**
   *
   * @type {boolean}
   * @memberof LoggerInsertConfigRequest
   */
  enabled?: boolean
  /**
   *
   * @type {number}
   * @memberof LoggerInsertConfigRequest
   */
  object_id?: number
  /**
   *
   * @type {string}
   * @memberof LoggerInsertConfigRequest
   */
  period?: string
  /**
   *
   * @type {number}
   * @memberof LoggerInsertConfigRequest
   */
  storage_id?: number
}
