// tslint:disable
/**
 * Webitel API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 24.04.0
 * Contact: support@webitel.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface NEWSpaceSourceChanges
 */
export interface NEWSpaceSourceChanges {
  /**
   * BIO. Short description about the space. OPTIONAL. Multi-lined text.
   * @type {string}
   * @memberof NEWSpaceSourceChanges
   */
  home_page?: string
  /**
   * Represents the name of the knowledge base space.
   * @type {string}
   * @memberof NEWSpaceSourceChanges
   */
  name?: string
  /**
   * The state of the space.
   * @type {boolean}
   * @memberof NEWSpaceSourceChanges
   */
  state?: boolean
}
