// tslint:disable
/**
 * Webitel API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 24.04.0
 * Contact: support@webitel.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as globalImportUrl from 'url'
import globalAxios, { AxiosPromise, AxiosInstance } from 'axios'
import { Configuration } from '../configuration'
// Some imports not used depending on template conditions
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  RequestArgs,
  BaseAPI,
  RequiredError,
} from '../base'
// @ts-ignore
import { InlineObject3 } from '../api'
// @ts-ignore
import { InlineObject4 } from '../api'
// @ts-ignore
import { RpcStatus } from '../api'
// @ts-ignore
import { WfmCreateShiftTemplateRequest } from '../api'
// @ts-ignore
import { WfmCreateShiftTemplateResponse } from '../api'
// @ts-ignore
import { WfmDeleteShiftTemplateResponse } from '../api'
// @ts-ignore
import { WfmReadShiftTemplateResponse } from '../api'
// @ts-ignore
import { WfmSearchShiftTemplateResponse } from '../api'
// @ts-ignore
import { WfmSearchShiftTemplateTimeResponse } from '../api'
// @ts-ignore
import { WfmUpdateShiftTemplateResponse } from '../api'
// @ts-ignore
import { WfmUpdateShiftTemplateTimeBulkResponse } from '../api'
/**
 * ShiftTemplateServiceApi - axios parameter creator
 * @export
 */
export const ShiftTemplateServiceApiAxiosParamCreator = function(
  configuration?: Configuration
) {
  return {
    /**
     *
     * @param {WfmCreateShiftTemplateRequest} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createShiftTemplate: async (
      body: WfmCreateShiftTemplateRequest,
      options: any = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'body' is not null or undefined
      if (body === null || body === undefined) {
        throw new RequiredError(
          'body',
          'Required parameter body was null or undefined when calling createShiftTemplate.'
        )
      }
      const localVarPath = `/wfm/lookups/shift_templates`
      const localVarUrlObj = globalImportUrl.parse(localVarPath, true)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }
      const localVarRequestOptions = {
        method: 'POST',
        ...baseOptions,
        ...options,
      }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication AccessToken required
      if (configuration && configuration.apiKey) {
        const localVarApiKeyValue =
          typeof configuration.apiKey === 'function'
            ? await configuration.apiKey('X-Webitel-Access')
            : await configuration.apiKey
        localVarHeaderParameter['X-Webitel-Access'] = localVarApiKeyValue
      }

      localVarHeaderParameter['Content-Type'] = 'application/json'

      localVarUrlObj.query = {
        ...localVarUrlObj.query,
        ...localVarQueryParameter,
        ...options.query,
      }
      // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
      delete localVarUrlObj.search
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      }
      const needsSerialization =
        typeof body !== 'string' ||
        localVarRequestOptions.headers['Content-Type'] === 'application/json'
      localVarRequestOptions.data = needsSerialization
        ? JSON.stringify(body !== undefined ? body : {})
        : body || ''

      return {
        url: globalImportUrl.format(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     *
     * @param {string} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteShiftTemplate: async (
      id: string,
      options: any = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      if (id === null || id === undefined) {
        throw new RequiredError(
          'id',
          'Required parameter id was null or undefined when calling deleteShiftTemplate.'
        )
      }
      const localVarPath = `/wfm/lookups/shift_templates/{id}`.replace(
        `{${'id'}}`,
        encodeURIComponent(String(id))
      )
      const localVarUrlObj = globalImportUrl.parse(localVarPath, true)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }
      const localVarRequestOptions = {
        method: 'DELETE',
        ...baseOptions,
        ...options,
      }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication AccessToken required
      if (configuration && configuration.apiKey) {
        const localVarApiKeyValue =
          typeof configuration.apiKey === 'function'
            ? await configuration.apiKey('X-Webitel-Access')
            : await configuration.apiKey
        localVarHeaderParameter['X-Webitel-Access'] = localVarApiKeyValue
      }

      localVarUrlObj.query = {
        ...localVarUrlObj.query,
        ...localVarQueryParameter,
        ...options.query,
      }
      // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
      delete localVarUrlObj.search
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      }

      return {
        url: globalImportUrl.format(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     *
     * @param {string} id
     * @param {Array<string>} [fields]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    readShiftTemplate: async (
      id: string,
      fields?: Array<string>,
      options: any = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      if (id === null || id === undefined) {
        throw new RequiredError(
          'id',
          'Required parameter id was null or undefined when calling readShiftTemplate.'
        )
      }
      const localVarPath = `/wfm/lookups/shift_templates/{id}`.replace(
        `{${'id'}}`,
        encodeURIComponent(String(id))
      )
      const localVarUrlObj = globalImportUrl.parse(localVarPath, true)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }
      const localVarRequestOptions = {
        method: 'GET',
        ...baseOptions,
        ...options,
      }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication AccessToken required
      if (configuration && configuration.apiKey) {
        const localVarApiKeyValue =
          typeof configuration.apiKey === 'function'
            ? await configuration.apiKey('X-Webitel-Access')
            : await configuration.apiKey
        localVarHeaderParameter['X-Webitel-Access'] = localVarApiKeyValue
      }

      if (fields) {
        localVarQueryParameter['fields'] = fields
      }

      localVarUrlObj.query = {
        ...localVarUrlObj.query,
        ...localVarQueryParameter,
        ...options.query,
      }
      // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
      delete localVarUrlObj.search
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      }

      return {
        url: globalImportUrl.format(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     *
     * @param {string} [q]
     * @param {number} [page]
     * @param {number} [size]
     * @param {string} [sort]
     * @param {Array<string>} [fields]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    searchShiftTemplate: async (
      q?: string,
      page?: number,
      size?: number,
      sort?: string,
      fields?: Array<string>,
      options: any = {}
    ): Promise<RequestArgs> => {
      const localVarPath = `/wfm/lookups/shift_templates`
      const localVarUrlObj = globalImportUrl.parse(localVarPath, true)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }
      const localVarRequestOptions = {
        method: 'GET',
        ...baseOptions,
        ...options,
      }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication AccessToken required
      if (configuration && configuration.apiKey) {
        const localVarApiKeyValue =
          typeof configuration.apiKey === 'function'
            ? await configuration.apiKey('X-Webitel-Access')
            : await configuration.apiKey
        localVarHeaderParameter['X-Webitel-Access'] = localVarApiKeyValue
      }

      if (q !== undefined) {
        localVarQueryParameter['q'] = q
      }

      if (page !== undefined) {
        localVarQueryParameter['page'] = page
      }

      if (size !== undefined) {
        localVarQueryParameter['size'] = size
      }

      if (sort !== undefined) {
        localVarQueryParameter['sort'] = sort
      }

      if (fields) {
        localVarQueryParameter['fields'] = fields
      }

      localVarUrlObj.query = {
        ...localVarUrlObj.query,
        ...localVarQueryParameter,
        ...options.query,
      }
      // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
      delete localVarUrlObj.search
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      }

      return {
        url: globalImportUrl.format(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     *
     * @summary SearchShiftTemplateTime returns a list of pause template times.
     * @param {string} shiftTemplateId
     * @param {string} [q]
     * @param {number} [page]
     * @param {number} [size]
     * @param {string} [sort]
     * @param {Array<string>} [fields]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    searchShiftTemplateTime: async (
      shiftTemplateId: string,
      q?: string,
      page?: number,
      size?: number,
      sort?: string,
      fields?: Array<string>,
      options: any = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'shiftTemplateId' is not null or undefined
      if (shiftTemplateId === null || shiftTemplateId === undefined) {
        throw new RequiredError(
          'shiftTemplateId',
          'Required parameter shiftTemplateId was null or undefined when calling searchShiftTemplateTime.'
        )
      }
      const localVarPath = `/wfm/lookups/shift_templates/{shift_template_id}/times`.replace(
        `{${'shift_template_id'}}`,
        encodeURIComponent(String(shiftTemplateId))
      )
      const localVarUrlObj = globalImportUrl.parse(localVarPath, true)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }
      const localVarRequestOptions = {
        method: 'GET',
        ...baseOptions,
        ...options,
      }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication AccessToken required
      if (configuration && configuration.apiKey) {
        const localVarApiKeyValue =
          typeof configuration.apiKey === 'function'
            ? await configuration.apiKey('X-Webitel-Access')
            : await configuration.apiKey
        localVarHeaderParameter['X-Webitel-Access'] = localVarApiKeyValue
      }

      if (q !== undefined) {
        localVarQueryParameter['q'] = q
      }

      if (page !== undefined) {
        localVarQueryParameter['page'] = page
      }

      if (size !== undefined) {
        localVarQueryParameter['size'] = size
      }

      if (sort !== undefined) {
        localVarQueryParameter['sort'] = sort
      }

      if (fields) {
        localVarQueryParameter['fields'] = fields
      }

      localVarUrlObj.query = {
        ...localVarUrlObj.query,
        ...localVarQueryParameter,
        ...options.query,
      }
      // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
      delete localVarUrlObj.search
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      }

      return {
        url: globalImportUrl.format(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     *
     * @param {string} id
     * @param {InlineObject3} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateShiftTemplate: async (
      id: string,
      body: InlineObject3,
      options: any = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'id' is not null or undefined
      if (id === null || id === undefined) {
        throw new RequiredError(
          'id',
          'Required parameter id was null or undefined when calling updateShiftTemplate.'
        )
      }
      // verify required parameter 'body' is not null or undefined
      if (body === null || body === undefined) {
        throw new RequiredError(
          'body',
          'Required parameter body was null or undefined when calling updateShiftTemplate.'
        )
      }
      const localVarPath = `/wfm/lookups/shift_templates/{id}`.replace(
        `{${'id'}}`,
        encodeURIComponent(String(id))
      )
      const localVarUrlObj = globalImportUrl.parse(localVarPath, true)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }
      const localVarRequestOptions = {
        method: 'PUT',
        ...baseOptions,
        ...options,
      }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication AccessToken required
      if (configuration && configuration.apiKey) {
        const localVarApiKeyValue =
          typeof configuration.apiKey === 'function'
            ? await configuration.apiKey('X-Webitel-Access')
            : await configuration.apiKey
        localVarHeaderParameter['X-Webitel-Access'] = localVarApiKeyValue
      }

      localVarHeaderParameter['Content-Type'] = 'application/json'

      localVarUrlObj.query = {
        ...localVarUrlObj.query,
        ...localVarQueryParameter,
        ...options.query,
      }
      // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
      delete localVarUrlObj.search
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      }
      const needsSerialization =
        typeof body !== 'string' ||
        localVarRequestOptions.headers['Content-Type'] === 'application/json'
      localVarRequestOptions.data = needsSerialization
        ? JSON.stringify(body !== undefined ? body : {})
        : body || ''

      return {
        url: globalImportUrl.format(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
    /**
     *
     * @summary UpdateShiftTemplateTimeBulk updates a list of shift template times. Update existing, create that not exists in database and delete that not exists in the list.
     * @param {string} shiftTemplateId
     * @param {InlineObject4} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateShiftTemplateTimeBulk: async (
      shiftTemplateId: string,
      body: InlineObject4,
      options: any = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'shiftTemplateId' is not null or undefined
      if (shiftTemplateId === null || shiftTemplateId === undefined) {
        throw new RequiredError(
          'shiftTemplateId',
          'Required parameter shiftTemplateId was null or undefined when calling updateShiftTemplateTimeBulk.'
        )
      }
      // verify required parameter 'body' is not null or undefined
      if (body === null || body === undefined) {
        throw new RequiredError(
          'body',
          'Required parameter body was null or undefined when calling updateShiftTemplateTimeBulk.'
        )
      }
      const localVarPath = `/wfm/lookups/shift_templates/{shift_template_id}/times`.replace(
        `{${'shift_template_id'}}`,
        encodeURIComponent(String(shiftTemplateId))
      )
      const localVarUrlObj = globalImportUrl.parse(localVarPath, true)
      let baseOptions
      if (configuration) {
        baseOptions = configuration.baseOptions
      }
      const localVarRequestOptions = {
        method: 'PUT',
        ...baseOptions,
        ...options,
      }
      const localVarHeaderParameter = {} as any
      const localVarQueryParameter = {} as any

      // authentication AccessToken required
      if (configuration && configuration.apiKey) {
        const localVarApiKeyValue =
          typeof configuration.apiKey === 'function'
            ? await configuration.apiKey('X-Webitel-Access')
            : await configuration.apiKey
        localVarHeaderParameter['X-Webitel-Access'] = localVarApiKeyValue
      }

      localVarHeaderParameter['Content-Type'] = 'application/json'

      localVarUrlObj.query = {
        ...localVarUrlObj.query,
        ...localVarQueryParameter,
        ...options.query,
      }
      // fix override query string Detail: https://stackoverflow.com/a/7517673/1077943
      delete localVarUrlObj.search
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {}
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      }
      const needsSerialization =
        typeof body !== 'string' ||
        localVarRequestOptions.headers['Content-Type'] === 'application/json'
      localVarRequestOptions.data = needsSerialization
        ? JSON.stringify(body !== undefined ? body : {})
        : body || ''

      return {
        url: globalImportUrl.format(localVarUrlObj),
        options: localVarRequestOptions,
      }
    },
  }
}

/**
 * ShiftTemplateServiceApi - functional programming interface
 * @export
 */
export const ShiftTemplateServiceApiFp = function(
  configuration?: Configuration
) {
  return {
    /**
     *
     * @param {WfmCreateShiftTemplateRequest} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async createShiftTemplate(
      body: WfmCreateShiftTemplateRequest,
      options?: any
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string
      ) => AxiosPromise<WfmCreateShiftTemplateResponse>
    > {
      const localVarAxiosArgs = await ShiftTemplateServiceApiAxiosParamCreator(
        configuration
      ).createShiftTemplate(body, options)
      return (
        axios: AxiosInstance = globalAxios,
        basePath: string = BASE_PATH
      ) => {
        const axiosRequestArgs = {
          ...localVarAxiosArgs.options,
          url: basePath + localVarAxiosArgs.url,
        }
        return axios.request(axiosRequestArgs)
      }
    },
    /**
     *
     * @param {string} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async deleteShiftTemplate(
      id: string,
      options?: any
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string
      ) => AxiosPromise<WfmDeleteShiftTemplateResponse>
    > {
      const localVarAxiosArgs = await ShiftTemplateServiceApiAxiosParamCreator(
        configuration
      ).deleteShiftTemplate(id, options)
      return (
        axios: AxiosInstance = globalAxios,
        basePath: string = BASE_PATH
      ) => {
        const axiosRequestArgs = {
          ...localVarAxiosArgs.options,
          url: basePath + localVarAxiosArgs.url,
        }
        return axios.request(axiosRequestArgs)
      }
    },
    /**
     *
     * @param {string} id
     * @param {Array<string>} [fields]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async readShiftTemplate(
      id: string,
      fields?: Array<string>,
      options?: any
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string
      ) => AxiosPromise<WfmReadShiftTemplateResponse>
    > {
      const localVarAxiosArgs = await ShiftTemplateServiceApiAxiosParamCreator(
        configuration
      ).readShiftTemplate(id, fields, options)
      return (
        axios: AxiosInstance = globalAxios,
        basePath: string = BASE_PATH
      ) => {
        const axiosRequestArgs = {
          ...localVarAxiosArgs.options,
          url: basePath + localVarAxiosArgs.url,
        }
        return axios.request(axiosRequestArgs)
      }
    },
    /**
     *
     * @param {string} [q]
     * @param {number} [page]
     * @param {number} [size]
     * @param {string} [sort]
     * @param {Array<string>} [fields]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async searchShiftTemplate(
      q?: string,
      page?: number,
      size?: number,
      sort?: string,
      fields?: Array<string>,
      options?: any
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string
      ) => AxiosPromise<WfmSearchShiftTemplateResponse>
    > {
      const localVarAxiosArgs = await ShiftTemplateServiceApiAxiosParamCreator(
        configuration
      ).searchShiftTemplate(q, page, size, sort, fields, options)
      return (
        axios: AxiosInstance = globalAxios,
        basePath: string = BASE_PATH
      ) => {
        const axiosRequestArgs = {
          ...localVarAxiosArgs.options,
          url: basePath + localVarAxiosArgs.url,
        }
        return axios.request(axiosRequestArgs)
      }
    },
    /**
     *
     * @summary SearchShiftTemplateTime returns a list of pause template times.
     * @param {string} shiftTemplateId
     * @param {string} [q]
     * @param {number} [page]
     * @param {number} [size]
     * @param {string} [sort]
     * @param {Array<string>} [fields]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async searchShiftTemplateTime(
      shiftTemplateId: string,
      q?: string,
      page?: number,
      size?: number,
      sort?: string,
      fields?: Array<string>,
      options?: any
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string
      ) => AxiosPromise<WfmSearchShiftTemplateTimeResponse>
    > {
      const localVarAxiosArgs = await ShiftTemplateServiceApiAxiosParamCreator(
        configuration
      ).searchShiftTemplateTime(
        shiftTemplateId,
        q,
        page,
        size,
        sort,
        fields,
        options
      )
      return (
        axios: AxiosInstance = globalAxios,
        basePath: string = BASE_PATH
      ) => {
        const axiosRequestArgs = {
          ...localVarAxiosArgs.options,
          url: basePath + localVarAxiosArgs.url,
        }
        return axios.request(axiosRequestArgs)
      }
    },
    /**
     *
     * @param {string} id
     * @param {InlineObject3} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async updateShiftTemplate(
      id: string,
      body: InlineObject3,
      options?: any
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string
      ) => AxiosPromise<WfmUpdateShiftTemplateResponse>
    > {
      const localVarAxiosArgs = await ShiftTemplateServiceApiAxiosParamCreator(
        configuration
      ).updateShiftTemplate(id, body, options)
      return (
        axios: AxiosInstance = globalAxios,
        basePath: string = BASE_PATH
      ) => {
        const axiosRequestArgs = {
          ...localVarAxiosArgs.options,
          url: basePath + localVarAxiosArgs.url,
        }
        return axios.request(axiosRequestArgs)
      }
    },
    /**
     *
     * @summary UpdateShiftTemplateTimeBulk updates a list of shift template times. Update existing, create that not exists in database and delete that not exists in the list.
     * @param {string} shiftTemplateId
     * @param {InlineObject4} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async updateShiftTemplateTimeBulk(
      shiftTemplateId: string,
      body: InlineObject4,
      options?: any
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string
      ) => AxiosPromise<WfmUpdateShiftTemplateTimeBulkResponse>
    > {
      const localVarAxiosArgs = await ShiftTemplateServiceApiAxiosParamCreator(
        configuration
      ).updateShiftTemplateTimeBulk(shiftTemplateId, body, options)
      return (
        axios: AxiosInstance = globalAxios,
        basePath: string = BASE_PATH
      ) => {
        const axiosRequestArgs = {
          ...localVarAxiosArgs.options,
          url: basePath + localVarAxiosArgs.url,
        }
        return axios.request(axiosRequestArgs)
      }
    },
  }
}

/**
 * ShiftTemplateServiceApi - factory interface
 * @export
 */
export const ShiftTemplateServiceApiFactory = function(
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance
) {
  return {
    /**
     *
     * @param {WfmCreateShiftTemplateRequest} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createShiftTemplate(
      body: WfmCreateShiftTemplateRequest,
      options?: any
    ): AxiosPromise<WfmCreateShiftTemplateResponse> {
      return ShiftTemplateServiceApiFp(configuration)
        .createShiftTemplate(body, options)
        .then((request) => request(axios, basePath))
    },
    /**
     *
     * @param {string} id
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteShiftTemplate(
      id: string,
      options?: any
    ): AxiosPromise<WfmDeleteShiftTemplateResponse> {
      return ShiftTemplateServiceApiFp(configuration)
        .deleteShiftTemplate(id, options)
        .then((request) => request(axios, basePath))
    },
    /**
     *
     * @param {string} id
     * @param {Array<string>} [fields]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    readShiftTemplate(
      id: string,
      fields?: Array<string>,
      options?: any
    ): AxiosPromise<WfmReadShiftTemplateResponse> {
      return ShiftTemplateServiceApiFp(configuration)
        .readShiftTemplate(id, fields, options)
        .then((request) => request(axios, basePath))
    },
    /**
     *
     * @param {string} [q]
     * @param {number} [page]
     * @param {number} [size]
     * @param {string} [sort]
     * @param {Array<string>} [fields]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    searchShiftTemplate(
      q?: string,
      page?: number,
      size?: number,
      sort?: string,
      fields?: Array<string>,
      options?: any
    ): AxiosPromise<WfmSearchShiftTemplateResponse> {
      return ShiftTemplateServiceApiFp(configuration)
        .searchShiftTemplate(q, page, size, sort, fields, options)
        .then((request) => request(axios, basePath))
    },
    /**
     *
     * @summary SearchShiftTemplateTime returns a list of pause template times.
     * @param {string} shiftTemplateId
     * @param {string} [q]
     * @param {number} [page]
     * @param {number} [size]
     * @param {string} [sort]
     * @param {Array<string>} [fields]
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    searchShiftTemplateTime(
      shiftTemplateId: string,
      q?: string,
      page?: number,
      size?: number,
      sort?: string,
      fields?: Array<string>,
      options?: any
    ): AxiosPromise<WfmSearchShiftTemplateTimeResponse> {
      return ShiftTemplateServiceApiFp(configuration)
        .searchShiftTemplateTime(
          shiftTemplateId,
          q,
          page,
          size,
          sort,
          fields,
          options
        )
        .then((request) => request(axios, basePath))
    },
    /**
     *
     * @param {string} id
     * @param {InlineObject3} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateShiftTemplate(
      id: string,
      body: InlineObject3,
      options?: any
    ): AxiosPromise<WfmUpdateShiftTemplateResponse> {
      return ShiftTemplateServiceApiFp(configuration)
        .updateShiftTemplate(id, body, options)
        .then((request) => request(axios, basePath))
    },
    /**
     *
     * @summary UpdateShiftTemplateTimeBulk updates a list of shift template times. Update existing, create that not exists in database and delete that not exists in the list.
     * @param {string} shiftTemplateId
     * @param {InlineObject4} body
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateShiftTemplateTimeBulk(
      shiftTemplateId: string,
      body: InlineObject4,
      options?: any
    ): AxiosPromise<WfmUpdateShiftTemplateTimeBulkResponse> {
      return ShiftTemplateServiceApiFp(configuration)
        .updateShiftTemplateTimeBulk(shiftTemplateId, body, options)
        .then((request) => request(axios, basePath))
    },
  }
}

/**
 * ShiftTemplateServiceApi - object-oriented interface
 * @export
 * @class ShiftTemplateServiceApi
 * @extends {BaseAPI}
 */
export class ShiftTemplateServiceApi extends BaseAPI {
  /**
   *
   * @param {WfmCreateShiftTemplateRequest} body
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ShiftTemplateServiceApi
   */
  public createShiftTemplate(
    body: WfmCreateShiftTemplateRequest,
    options?: any
  ) {
    return ShiftTemplateServiceApiFp(this.configuration)
      .createShiftTemplate(body, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   *
   * @param {string} id
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ShiftTemplateServiceApi
   */
  public deleteShiftTemplate(id: string, options?: any) {
    return ShiftTemplateServiceApiFp(this.configuration)
      .deleteShiftTemplate(id, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   *
   * @param {string} id
   * @param {Array<string>} [fields]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ShiftTemplateServiceApi
   */
  public readShiftTemplate(id: string, fields?: Array<string>, options?: any) {
    return ShiftTemplateServiceApiFp(this.configuration)
      .readShiftTemplate(id, fields, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   *
   * @param {string} [q]
   * @param {number} [page]
   * @param {number} [size]
   * @param {string} [sort]
   * @param {Array<string>} [fields]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ShiftTemplateServiceApi
   */
  public searchShiftTemplate(
    q?: string,
    page?: number,
    size?: number,
    sort?: string,
    fields?: Array<string>,
    options?: any
  ) {
    return ShiftTemplateServiceApiFp(this.configuration)
      .searchShiftTemplate(q, page, size, sort, fields, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   *
   * @summary SearchShiftTemplateTime returns a list of pause template times.
   * @param {string} shiftTemplateId
   * @param {string} [q]
   * @param {number} [page]
   * @param {number} [size]
   * @param {string} [sort]
   * @param {Array<string>} [fields]
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ShiftTemplateServiceApi
   */
  public searchShiftTemplateTime(
    shiftTemplateId: string,
    q?: string,
    page?: number,
    size?: number,
    sort?: string,
    fields?: Array<string>,
    options?: any
  ) {
    return ShiftTemplateServiceApiFp(this.configuration)
      .searchShiftTemplateTime(
        shiftTemplateId,
        q,
        page,
        size,
        sort,
        fields,
        options
      )
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   *
   * @param {string} id
   * @param {InlineObject3} body
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ShiftTemplateServiceApi
   */
  public updateShiftTemplate(id: string, body: InlineObject3, options?: any) {
    return ShiftTemplateServiceApiFp(this.configuration)
      .updateShiftTemplate(id, body, options)
      .then((request) => request(this.axios, this.basePath))
  }

  /**
   *
   * @summary UpdateShiftTemplateTimeBulk updates a list of shift template times. Update existing, create that not exists in database and delete that not exists in the list.
   * @param {string} shiftTemplateId
   * @param {InlineObject4} body
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof ShiftTemplateServiceApi
   */
  public updateShiftTemplateTimeBulk(
    shiftTemplateId: string,
    body: InlineObject4,
    options?: any
  ) {
    return ShiftTemplateServiceApiFp(this.configuration)
      .updateShiftTemplateTimeBulk(shiftTemplateId, body, options)
      .then((request) => request(this.axios, this.basePath))
  }
}
