// tslint:disable
/**
 * Webitel API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 24.04.0
 * Contact: support@webitel.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { StorageUploadFileChannel } from './storage-upload-file-channel'

/**
 *
 * @export
 * @interface StorageCreateFilePolicyRequest
 */
export interface StorageCreateFilePolicyRequest {
  /**
   *
   * @type {Array<StorageUploadFileChannel>}
   * @memberof StorageCreateFilePolicyRequest
   */
  channels?: Array<StorageUploadFileChannel>
  /**
   *
   * @type {string}
   * @memberof StorageCreateFilePolicyRequest
   */
  description?: string
  /**
   *
   * @type {boolean}
   * @memberof StorageCreateFilePolicyRequest
   */
  enabled?: boolean
  /**
   *
   * @type {string}
   * @memberof StorageCreateFilePolicyRequest
   */
  max_upload_size?: string
  /**
   *
   * @type {Array<string>}
   * @memberof StorageCreateFilePolicyRequest
   */
  mime_types?: Array<string>
  /**
   *
   * @type {string}
   * @memberof StorageCreateFilePolicyRequest
   */
  name?: string
  /**
   *
   * @type {number}
   * @memberof StorageCreateFilePolicyRequest
   */
  retention_days?: number
  /**
   *
   * @type {string}
   * @memberof StorageCreateFilePolicyRequest
   */
  speed_download?: string
  /**
   *
   * @type {string}
   * @memberof StorageCreateFilePolicyRequest
   */
  speed_upload?: string
}
