// tslint:disable
/**
 * Webitel API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 24.04.0
 * Contact: support@webitel.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { StorageFile } from './storage-file'

/**
 *
 * @export
 * @interface StorageListFile
 */
export interface StorageListFile {
  /**
   *
   * @type {Array<StorageFile>}
   * @memberof StorageListFile
   */
  items?: Array<StorageFile>
  /**
   *
   * @type {boolean}
   * @memberof StorageListFile
   */
  next?: boolean
}
