// tslint:disable
/**
 * Webitel API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 24.04.0
 * Contact: support@webitel.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface WebitelContactsInputDynamicCondition
 */
export interface WebitelContactsInputDynamicCondition {
  /**
   * The ID of the assignee that should be assigned if the condition is met (optional).
   * @type {string}
   * @memberof WebitelContactsInputDynamicCondition
   */
  assignee?: string
  /**
   * The query or condition expression used to evaluate the group.
   * @type {string}
   * @memberof WebitelContactsInputDynamicCondition
   */
  expression?: string
  /**
   * The ID of the static group that should be assigned if the condition is met.
   * @type {string}
   * @memberof WebitelContactsInputDynamicCondition
   */
  group?: string
}
