// tslint:disable
/**
 * Webitel API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 24.04.0
 * Contact: support@webitel.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { WfmAgentWorkingSchedule } from './wfm-agent-working-schedule'
import { WfmHoliday } from './wfm-holiday'

/**
 *
 * @export
 * @interface WfmSearchAgentsWorkingScheduleResponse
 */
export interface WfmSearchAgentsWorkingScheduleResponse {
  /**
   *
   * @type {Array<WfmHoliday>}
   * @memberof WfmSearchAgentsWorkingScheduleResponse
   */
  holidays?: Array<WfmHoliday>
  /**
   *
   * @type {Array<WfmAgentWorkingSchedule>}
   * @memberof WfmSearchAgentsWorkingScheduleResponse
   */
  items?: Array<WfmAgentWorkingSchedule>
  /**
   *
   * @type {string}
   * @memberof WfmSearchAgentsWorkingScheduleResponse
   */
  total?: string
}
