// tslint:disable
/**
 * Webitel API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 24.04.0
 * Contact: support@webitel.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { WfmLookupEntity } from './wfm-lookup-entity'

/**
 *
 * @export
 * @interface WfmForecastCalculation
 */
export interface WfmForecastCalculation {
  /**
   *
   * @type {string}
   * @memberof WfmForecastCalculation
   */
  created_at?: string
  /**
   *
   * @type {WfmLookupEntity}
   * @memberof WfmForecastCalculation
   */
  created_by?: WfmLookupEntity
  /**
   *
   * @type {string}
   * @memberof WfmForecastCalculation
   */
  description?: string
  /**
   *
   * @type {string}
   * @memberof WfmForecastCalculation
   */
  domain_id?: string
  /**
   *
   * @type {string}
   * @memberof WfmForecastCalculation
   */
  id?: string
  /**
   *
   * @type {string}
   * @memberof WfmForecastCalculation
   */
  name?: string
  /**
   *
   * @type {string}
   * @memberof WfmForecastCalculation
   */
  procedure?: string
  /**
   *
   * @type {string}
   * @memberof WfmForecastCalculation
   */
  updated_at?: string
  /**
   *
   * @type {WfmLookupEntity}
   * @memberof WfmForecastCalculation
   */
  updated_by?: WfmLookupEntity
}
