// tslint:disable
/**
 * Webitel API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 24.04.0
 * Contact: support@webitel.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @enum {string}
 */
export enum WfmWorkingScheduleState {
  UNSPECIFIED = 'WORKING_SCHEDULE_STATE_UNSPECIFIED',
  ACTIVE = 'WORKING_SCHEDULE_STATE_ACTIVE',
  PENDING = 'WORKING_SCHEDULE_STATE_PENDING',
  DRAFT = 'WORKING_SCHEDULE_STATE_DRAFT',
  ARCHIVED = 'WORKING_SCHEDULE_STATE_ARCHIVED',
}
